services:
  - type: web
    name: puppeteer-cleaner
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
